### ISSUE TITLE
https://discord.com/api/v9/guilds/{guild_id}/members

### ISSUE THREAD

**Issue by 2021php** [YusufBilgin/DiscordScraper#1]
GET https://discord.com/api/v9/guilds/{guild_id}/members
Authorization: token
response is
 `{
    "message": "Missing Access",
    "code": 50001
}`

**Comment by YusufBilgin** [comment]
I think that this [endpoint ](https://discord.com/developers/docs/resources/guild#list-guild-members)is only suitable for bots. Removed request from code 👍
